# Generated by Django 6.0.7 on 2026-07-11 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cunto',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cunto',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jimicsi',
            name='taariikhda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='routine90',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cunto',
            name='taariikhda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='routine90',
            name='maalinta',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dherer', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('miisaan_hadda', models.FloatField(blank=True, help_text='Current weight in kg', null=True)),
                ('hadaf', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miisaanka', models.FloatField()),
                ('taariikhda', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
